version: '2'
services:
    mysql:
      image: mysql:5.6
      container_name: ${PROJECT_NAME}-mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
        - "8306:3306"
    php:
        build: docker/php-fpm
        container_name: ${PROJECT_NAME}-php
        ports:
            - '9002:9000'
        volumes:
            - .:/var/www/usermanagement:cached
        links:
            - mysql
    nginx:
        build: docker/nginx
        container_name: ${PROJECT_NAME}-nginx
        ports:
            - '8080:80'
        links:
            - php
        volumes_from:
            - php